//---------------------------------------------------------------------
// Program: weather
//
// The Aercus 433Mhz weather station unit seems to run some software known
// as Weather logger (V 2.2).
// It's connected to my local area network, and pushes data to Weather
// Underground.
//
// I wanted to display some of the weather values on a Raspberry Pi
// zero w that has a Pimoroni Micro Dot pHAT display attached.
//
// Method:
// 1. I changed the configuration of the weather station so that it sends
// the weather data directly to the Rpi instead of to weather underground
// (I decided to do this after trying other methods that were unreliable)
//
// 2. Create a shared memory segment for the storage of weather variables
// that I want to see.
//
// 3. Open up a file descriptor for the I2C bus.
//
// 4. Open up a listening port to collect pushed data from the Aercus.
//
// 5. Fork a child process that reads shared memory and updates
// the I2c pHAT display with my chosen weather variables.
//
// 6. The Main process accepts inbound connections, extracts the
// variables from the incomming data and updates shared memory
// with the values I want. Main loops forever.
//
// Reason:
// The pHAT display displays each of the values in shm with a (DISPLAY_DELAY)
// delay. If this display has to pause each time new values are available
// it becomes quite ineffective. Running the update as a child process removes
// this problem.
//
// Notes:
// Error messages are written to syslog.
// If DEBUG is defined, weather variables are output to syslog.
// Typical response generated by the weather station is :
//
//"GET /weatherstation/updateweatherstation.php?ID=???????&PASSWORD=???????&tempf=46.9
//&humidity=81&dewptf=41.4&windchillf=45.3&winddir=271&windspeedmph=4.03&windgustmph=4.92
//&rainin=0.00&dailyrainin=0.09&weeklyrainin=0.80&monthlyrainin=2.27&yearlyrainin=2.27
//&solarradiation=16.66&UV=1&indoortempf=65.1&indoorhumidity=46&baromin=29.70
//&lowbatt=0&dateutc=2020-1-15%2014:23:38&softwaretype=WH2600GEN_V2.2.5&action=updateraw
//&realtime=1&rtfreq=5 HTTP/1.0 Accept: */* \r\nHost: 192.168.0.31 \r\nConnection: Close\r\n\r\n
//
// WR
//---------------------------------------------------------------------------
// Things you can change.
// DISPLAY_CURRENT has a max value of 7 (which equates to 75ma. See bright.c).
// I've not set it above 4. Increase this at your own risk!!
//-----------------------------------------------------------------------------
//#define DEBUG
#define DISPLAY_DELAY 2
#define DISPLAY_CURRENT 4
#define DISPLAY_PWM 7
#define SERVER_PORT 8888
#define DISPLAY_FIELD_COUNT 6
//-----------------------------------------------------------------------------
// End of normal things to change
//-----------------------------------------------------------------------------
#include <linux/i2c-dev.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/socket.h>
#include <unistd.h>
#include <sys/types.h>
#include <arpa/inet.h>
#include <sys/ioctl.h>
#include <fcntl.h>
#include <stdint.h>
#include <errno.h>
#include <syslog.h>
#include <sys/mman.h>
struct sockaddr_in server_address;
int sockfd=-1;
#include "funcs.h"

int main() {
struct sockaddr_in client;
int bytes_returned;
char input_line[20000];
int i2c_fd,pid,k,l,c;
int client_sock;
float pooh;
void *shmem;
char outTemp[10],outHumi[10],dewptf[10],windchillf[10],dailyrainmm[10];
char winddir[10],avgwind[10],gustspeed[10],rainin[10],weeklyrainin[10];
char dailyrainin[10],monthlyrainin[10],yearlyrainin[10],inTemp[10];
char solarradiation[10],indoortempf[10],inHumi[10],RelPress[10];

        //-------------------------------------------------------------------------
        // initialise all the bits needed before running the main program loop.
        //--------------------------------------------------------------------------
        shmem = create_shm(200);        //Create some shared memory.
                                        //The dot pHAT can only display 6 characters at a time.
                                        //10 bytes of storage are allocated for each weather value.
                                        //Each value is stored sequentially with an offset of +10
                                        //I only want a few of the values, so there's space here if
                                        //you want some of the ones I ignore.
        if(shmem == (void *) -1) {
                syslog(LOG_NOTICE,"Could not create shared memory segment. Quitting\n");
                exit(EXIT_FAILURE);
        }
        memset(shmem,0,200);            //Clear the shared memory out because it seems the right
                                        //thing to do.


        //------------------------------------------------------------------
        //Open the i2c connection. Note that this won't work unless you are
        //ivoking it from a user that has the right permissions. If you run
        //this program as a daemon by systemctl all should be good. See
        //file weather.service within this repo.
        //------------------------------------------------------------------
        i2c_fd = open("/dev/i2c-1", O_RDWR);
        if(i2c_fd<=0) {
                syslog(LOG_NOTICE,"Could not open device /dev/i2c-1 so have to exit\n");
                munmap(shmem,200);
                exit(EXIT_FAILURE);
        }
        create_listen_socket(SERVER_PORT);      //Create a listening socket on port 8888
        c = sizeof(struct sockaddr_in);
        pid=fork();                             //Fork. Main listens for data from the
                                                //weather server and writes values to
                                                //shm. Child reads shm and updates diplay
        //-------------------------------------------------------------------------
        // Initialisation finished
        //-------------------------------------------------------------------------
        if(pid ==0) {
                //----------------------------------------------------
                // This is the child. It just updates the mdot display
                // based on what's stored in shared memory.
                // Each weather value is stored at a +10 offset from
                // the start of the shm.
                //----------------------------------------------------
                l=DISPLAY_FIELD_COUNT*10;
                while(1) {
                        for(k=0;k<l;k+=10) {
                                reset(i2c_fd);
                                bright(i2c_fd,DISPLAY_CURRENT,DISPLAY_PWM);
                                printstr(i2c_fd, shmem+k);
                                update(i2c_fd);
                                sleep(DISPLAY_DELAY);
                        }
                }
        }
        //----------------------------------------------
        // Main process. Collect data and update shmem.
        //-------------------------------------------------
        while(1) {
                client_sock = accept(sockfd, (struct sockaddr *) &client, (socklen_t*)&c);
                bytes_returned =read(client_sock ,input_line , sizeof(input_line));
                if(bytes_returned<0) {
                        syslog(LOG_NOTICE,"Server read returned %d (%s). Exiting\n",errno,strerror(errno));
                        exit(EXIT_FAILURE);
                }
                close(client_sock);
                //------------------------------------------------------------
                // Extract the values out of the live data push
                //------------------------------------------------------------
                if(bytes_returned>0) {
                        extract_values(input_line,"&tempf=","&", outTemp);
                        extract_values(input_line,"&humidity=","&",outHumi);
                        extract_values(input_line,"&dewptf=","&",dewptf);
                        extract_values(input_line,"&windchillf=","&",windchillf);
                        extract_values(input_line,"&winddir=","&",winddir);
                        extract_values(input_line,"&windspeedmph=","&",avgwind);
                        extract_values(input_line,"&windgustmph=","&",gustspeed);
                        extract_values(input_line,"&rainin=","&",rainin);
                        extract_values(input_line,"&dailyrainin=","&",dailyrainin);
                        extract_values(input_line,"&weeklyrainin=","&",weeklyrainin);
                        extract_values(input_line,"&monthlyrainin=","&",monthlyrainin);
                        extract_values(input_line,"&yearlyrainin=","&",yearlyrainin);
                        extract_values(input_line,"&solarradiation=","&",solarradiation);
                        extract_values(input_line,"&indoortempf=","&",indoortempf);
                        extract_values(input_line,"&indoorhumidity=","&",inHumi);
                        extract_values(input_line,"&baromin=","&",RelPress);
                        //--------------------------------------------------
                        // Deal with the values I care about
                        //--------------------------------------------------
                        strcat(outHumi,"%");
                        strcat(inHumi,"%");
                        sprintf(RelPress,"%.1f",(strtof(RelPress,NULL)*33.86));
                        sprintf(outTemp,"%.1fc",(((strtof(outTemp,NULL)-32)/9)*5));                        
                        sprintf(inTemp,"%.1fc",(((strtof(indoortempf,NULL)-32)/9)*5));

                        
                        pooh=strtof(dailyrainin,NULL);
                        pooh=pooh*25.4;
                        sprintf(dailyrainmm,"%.1fmm",pooh);
                        if(strlen(avgwind)>4) avgwind[2]=0x00;
                        else avgwind[3]=0x00;
                        strcat(avgwind,"mph");
                        if(strlen(gustspeed)>5) gustspeed[5]=0x00;
                        else gustspeed[4]=0x00;
                        strcat(gustspeed,"g");
                        //----------------------------------------------------------------
                        // Copy these values into shared memory
                        // Change DISPLAY_FIELD_COUNT if you add to these else they
                        // won't get picked up.
                        //----------------------------------------------------------------
                        memcpy(shmem,RelPress,10);
                        memcpy(shmem+10,outHumi,10);
                        memcpy(shmem+20,dailyrainin,10);
                        memcpy(shmem+30,avgwind,10);
                        memcpy(shmem+40,gustspeed,10);
                        memcpy(shmem+50,outTemp,10);
                        #ifdef DEBUG
                        syslog(LOG_NOTICE,"%d: %s,%s,%s,%s,%s,%s,%s,%s,%s\n",bytes_returned,
                               outTemp,inTemp,outHumi,inHumi,dailyrainmm,RelPress,avgwind,gustspeed,solarradiation);
                        #endif
                }
        }
        //-----------------------------------------------------
        // What fun. Exit after a while(1) has completed.
        //-----------------------------------------------------
        return (EXIT_SUCCESS);
}
